FROM node:20-alpine as build

WORKDIR /app

COPY teamhub.ui/package.json teamhub.ui/package-lock.json* ./
RUN npm install

COPY teamhub.ui/ .

RUN npm run build

FROM nginx:alpine

COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
