FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app

RUN apt-get update && apt-get install -y libkrb5-dev

COPY . .
RUN dotnet restore TeamHub.sln
RUN dotnet publish TeamHub.API/TeamHub.API.csproj -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app

RUN apt-get update && apt-get install -y libkrb5-dev

COPY --from=build /app/out ./
ENTRYPOINT ["dotnet", "TeamHub.API.dll"]
